version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - SendGridApiKey=api-key
      - SendGridFromEmail=from-email
      - SendGridToEmail=to-email
      - UserHeaderKey=X-User
      - AzureWebJobsStorage=azure-storage-connection-string
