name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Api/Dockerfile
          push: true
          tags: latest

      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: snake-game-host
          # dns-name-label: snake-handin
          image: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
          ports: 8080
          environment-variables: |
            AzureWebJobsStorage=${{ secrets.AZURE_STORAGE }}
